# NOTE: DO NOT REMOVE THIS...
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS
# FIX THE ISSUE FOR WHY THIS COMMAND EXISTS

class EmptyCommand < Command
  def run(payload, client)
  end
end
